In [1]:
from imu_calibration import calibrator,dataCollector
from ellipsoid_fit_python.ellipsoid_fit import ellipsoid_plot
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import qwiic_icm20948
import ipywidgets as widgets

In [2]:
accelCal = calibrator('accelCenter','accelTrans')
magCal = calibrator('magCenter','magTrans')

In [3]:
print(accelCal.center)
print(accelCal.transformation)
print(magCal.center)
print(magCal.transformation)

[0.03610293 0.05574535 0.06814677]
[[ 1.0781034  -0.21431702 -0.07403659]
 [-0.21431702  0.71177901 -0.24391956]
 [-0.07403659 -0.24391956  1.04424741]]
[ -8.70981008 -12.91955642  17.3433582 ]
[[ 0.03083491 -0.00050753 -0.00018444]
 [-0.00050753  0.03017014 -0.00017897]
 [-0.00018444 -0.00017897  0.03039004]]
